import { test, expect } from '@playwright/test';

test.describe('Publish Wizard flow', () => {
    test('should allow an authenticated user to fill out the publish form', async ({ page }) => {
        // 1. Navigate to publish page
        await page.goto('/publish');

        // Check if redirect to login happens - if so, we can't fully test without auth mock
        // For this implementation, we assume a local dev environment where we might bypass auth or have it pre-configured
        const url = page.url();
        if (url.includes('/login') || url.includes('/sign-in') || await page.getByText('Ingresa para publicar').isVisible()) {
            console.log('Skipping full wizard test as auth is required.');
            // However, we can assert that the login prompt is visible
            await expect(page.getByText('Ingresa para publicar')).toBeVisible();
            return;
        }

        // Step 1: Basic Info
        await expect(page.getByText('Paso 1: Información básica')).toBeVisible();

        // Fill Type (defaults to Apartamento, let's keep it)
        // Select Operation
        await page.getByRole('button', { name: 'Venta', exact: true }).click();

        // Fill Title
        await page.getByPlaceholder('Ej: Espectacular apartamento sobre la rambla').fill('Test E2E Property Title');

        // Fill Address
        await page.getByPlaceholder('Calle, número, barrio o ciudad...').fill('Av. Italia 1234');

        // Select Dept/City (Assume geoData is loaded)
        // await page.locator('select').nth(1).selectOption('Montevideo'); // Department

        // Go to Step 2
        await page.getByRole('button', { name: 'Siguiente' }).click();

        // Step 2: Details
        await expect(page.getByText('Detalles & Multimedia')).toBeVisible();

        // Fill Specs
        await page.locator('select').first().selectOption('2'); // Bedrooms
        await page.locator('select').nth(1).selectOption('1'); // Bathrooms
        await page.getByPlaceholder('Ej: 85').fill('95'); // Area
        await page.getByPlaceholder('Importe').fill('185000'); // Price

        // Fill Description
        await page.getByPlaceholder('Escriba aquí los puntos fuertes de la propiedad...').fill('This is a test description generated by E2E test.');

        // Go to Step 3
        await page.getByRole('button', { name: 'Siguiente' }).click();

        // Step 3: Review
        await expect(page.getByText('Finalizar Publicación')).toBeVisible();

        // Fill Phone
        await page.getByPlaceholder('Ej: 099 123 456').fill('091234567');

        // Check Price Preview
        await expect(page.getByText('U$S 185,000')).toBeVisible();

        // Note: We won't click "PUBLICAR AHORA" to avoid polluting the DB unless it's a test DB
        // But we assert the button is visible and active
        const publishBtn = page.getByRole('button', { name: 'PUBLICAR AHORA' });
        await expect(publishBtn).toBeVisible();
        await expect(publishBtn).not.toBeDisabled();
    });
});
