import os

data_ts_files = [
    r"apps/portal/lib/data.ts",
    r"apps/inmobiliaria/lib/data.ts"
]

MOCK_DATA = """export const PROPERTIES: Property[] = [
    {
        id: "1",
        slug: "penthouse-pocitos-rambla",
        title: "Exclusivo Piso en la Rambla de Pocitos",
        description: "Vistas panorámicas al mar desde este espectacular piso. 3 dormitorios en suite más servicio completo.",
        type: "Apartamento",
        operation: "Venta",
        badge: "Exclusivo",
        badgeColor: "bg-slate-900",
        price: 850000,
        currency: "USD",
        pricePerM2: 3611,
        gastosComunes: 25000,
        bedrooms: 3,
        bathrooms: 4,
        area: 180,
        builtArea: 180,
        garages: 2,
        floors: 1,
        yearBuilt: 2015,
        department: "Montevideo",
        city: "Montevideo",
        neighborhood: "Pocitos",
        address: "Rambla República del Perú 1400",
        geolocation: { lat: -34.9150, lng: -56.1450 },
        viviendaPromovida: false,
        acceptedGuarantees: [],
        utilityStatus: { saneamiento: "conectado", gas: "cañería", agua: "OSE", electricidad: "UTE" },
        energyLabel: "C",
        images: [
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1600607686527-6fb886090705?q=80&w=2000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1600566752355-35792bedcfe1?q=80&w=2000&auto=format&fit=crop"
        ],
        amenities: ["Portería 24hs", "Losa Radiante", "Ascensor"],
        views: 342,
        publishedAt: "2026-02-15T09:00:00Z",
        updatedAt: "2026-02-17T10:30:00Z",
        featured: true,
        agentName: "María Rodríguez",
        agentPhone: "+598 99 111 222",
    },
    {
        id: "2",
        slug: "residencia-jardines-carrasco",
        title: "Minimalista en Jardines de Carrasco",
        description: "Diseño de vanguardia y máxima privacidad. Amplio living comedor con estufa a leña y salida directa al jardín.",
        type: "Casa",
        operation: "Venta",
        badge: "Destacado",
        badgeColor: "bg-emerald-600",
        price: 1100000,
        currency: "USD",
        pricePerM2: 0,
        gastosComunes: null,
        bedrooms: 4,
        bathrooms: 4,
        area: 800,
        builtArea: 350,
        garages: 3,
        floors: 2,
        yearBuilt: 2021,
        department: "Montevideo",
        city: "Montevideo",
        neighborhood: "Carrasco",
        address: "Av. Rivera 7500",
        geolocation: { lat: -34.8850, lng: -56.0600 },
        viviendaPromovida: false,
        acceptedGuarantees: [],
        utilityStatus: { saneamiento: "conectado", gas: "supergas", agua: "OSE", electricidad: "UTE" },
        energyLabel: "A",
        images: [
            "https://images.unsplash.com/photo-1600596542815-2a4d9fbea409?q=80&w=2000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=2000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=2000&auto=format&fit=crop"
        ],
        amenities: ["Piscina", "Parrillero", "Jardín"],
        views: 215,
        publishedAt: "2026-02-10T14:15:00Z",
        updatedAt: "2026-02-16T11:20:00Z",
        featured: true,
        agentName: "Juan Pérez",
        agentPhone: "+598 99 333 444",
    },
    {
        id: "4",
        slug: "local-comercial-punta-carretas",
        title: "Local Premium en Guipúzcoa",
        description: "Excelente vidriera sobre calle de diseño. 80m² en planta libre más entrepiso.",
        type: "Local Comercial",
        operation: "Venta",
        badge: "Inversión",
        badgeColor: "bg-purple-600",
        price: 280000,
        currency: "USD",
        pricePerM2: 3500,
        gastosComunes: 4500,
        bedrooms: 0,
        bathrooms: 1,
        area: 80,
        builtArea: 80,
        garages: 0,
        floors: 1,
        yearBuilt: 1990,
        department: "Montevideo",
        city: "Montevideo",
        neighborhood: "Punta Carretas",
        address: "21 de Setiembre 2800",
        geolocation: { lat: -34.9180, lng: -56.1550 },
        viviendaPromovida: false,
        acceptedGuarantees: [],
        utilityStatus: { saneamiento: "conectado", gas: "sin servicio", agua: "OSE", electricidad: "UTE" },
        energyLabel: "C",
        images: [
            "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=2000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=2000&auto=format&fit=crop"
        ],
        amenities: ["Aire Acondicionado", "Vidriera"],
        views: 120,
        publishedAt: "2026-02-14T11:00:00Z",
        updatedAt: "2026-02-14T11:00:00Z",
        featured: false,
        agentName: "Carlos Méndez",
        agentPhone: "+598 99 777 888",
    },
    {
        id: "5",
        slug: "chacra-jose-ignacio",
        title: "Chacra Marítima en José Ignacio",
        description: "5 hectáreas de paz absoluta con vista a la laguna.",
        type: "Chacra o Campo",
        operation: "Venta",
        badge: "Lifestyle",
        badgeColor: "bg-orange-600",
        price: 1200000,
        currency: "USD",
        pricePerM2: 24,
        gastosComunes: null,
        bedrooms: 3,
        bathrooms: 3,
        area: 50000,
        builtArea: 250,
        garages: 4,
        floors: 1,
        yearBuilt: 2010,
        department: "Maldonado",
        city: "José Ignacio",
        neighborhood: "José Ignacio",
        address: "Km 5",
        geolocation: { lat: -34.8300, lng: -54.6500 },
        viviendaPromovida: false,
        acceptedGuarantees: [],
        utilityStatus: { saneamiento: "pozo", gas: "supergas", agua: "pozo", electricidad: "mixto" },
        energyLabel: "B",
        images: [
            "https://images.unsplash.com/photo-1449844908441-8829872d2607?q=80&w=2000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=2000&auto=format&fit=crop"
        ],
        amenities: ["Piscina", "Parrillero", "Jardín"],
        views: 89,
        publishedAt: "2026-02-01T10:00:00Z",
        updatedAt: "2026-02-15T16:00:00Z",
        featured: true,
        agentName: "Sofia Williams",
        agentPhone: "+598 99 000 111",
    },
    {
        id: "7",
        slug: "casa-jardin-prado",
        title: "Hermosa Casa con Fondo - Prado",
        description: "Propiedad de época reciclada. Conserva vitrales y pisos de pinotea.",
        type: "Casa",
        operation: "Venta",
        badge: "Nuevo Ingreso",
        badgeColor: "bg-rose-500",
        price: 350000,
        currency: "USD",
        pricePerM2: 1750,
        gastosComunes: null,
        bedrooms: 3,
        bathrooms: 2,
        area: 450,
        builtArea: 200,
        garages: 2,
        floors: 1,
        yearBuilt: 1940,
        department: "Montevideo",
        city: "Montevideo",
        neighborhood: "Prado",
        address: "Av. 19 de Abril 3300",
        geolocation: { lat: -34.8600, lng: -56.2000 },
        viviendaPromovida: false,
        acceptedGuarantees: [],
        utilityStatus: { saneamiento: "conectado", gas: "cañería", agua: "OSE", electricidad: "UTE" },
        energyLabel: "D",
        images: [
            "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?q=80&w=2000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1484154218962-a197022b5858?q=80&w=2000&auto=format&fit=crop"
        ],
        amenities: ["Jardín", "Parrillero"],
        views: 145,
        publishedAt: "2026-02-18T10:00:00Z",
        updatedAt: "2026-02-18T10:00:00Z",
        featured: false,
        agentName: "Lucía Fernandez",
        agentPhone: "+598 99 123 456",
    },
    {
        id: "6",
        slug: "verano-playa-mansa",
        title: "Disfruta el Verano en Playa Mansa",
        description: "Piso alto con inmejorable vista al puerto y la isla Gorriti.",
        type: "Apartamento",
        operation: "Alquiler",
        badge: "Punta del Este",
        badgeColor: "bg-cyan-500",
        price: 2500,
        currency: "USD",
        pricePerM2: 0,
        gastosComunes: null,
        bedrooms: 2,
        bathrooms: 2,
        area: 90,
        builtArea: 90,
        garages: 1,
        floors: 1,
        yearBuilt: 2018,
        department: "Maldonado",
        city: "Punta del Este",
        neighborhood: "Playa Mansa",
        address: "Parada 3",
        geolocation: { lat: -34.9550, lng: -54.9450 },
        viviendaPromovida: false,
        acceptedGuarantees: ["Depósito"],
        utilityStatus: { saneamiento: "conectado", gas: "cañería", agua: "OSE", electricidad: "UTE" },
        energyLabel: "A",
        images: [
            "https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=2000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1574362848149-11496d93a7c7?q=80&w=2000&auto=format&fit=crop"
        ],
        amenities: ["Piscina", "Gimnasio", "Seguridad 24hs"],
        views: 410,
        publishedAt: "2026-01-15T12:00:00Z",
        updatedAt: "2026-02-17T12:00:00Z",
        featured: true,
        agentName: "Federico Lopez",
        agentPhone: "+598 99 888 999",
    },
    {
        id: "3",
        slug: "apartamento-estudiantes-cordon",
        title: "Ideal Estudiantes - Cordón Soho",
        description: "A pasos de Facultades y con excelente locomoción.",
        type: "Apartamento",
        operation: "Alquiler",
        badge: "Oportunidad",
        badgeColor: "bg-blue-500",
        price: 24000,
        currency: "UYU",
        pricePerM2: 0,
        gastosComunes: 3500,
        bedrooms: 1,
        bathrooms: 1,
        area: 40,
        builtArea: 40,
        garages: 0,
        floors: 1,
        yearBuilt: 2023,
        department: "Montevideo",
        city: "Montevideo",
        neighborhood: "Cordón",
        address: "1500",
        geolocation: { lat: -34.9080, lng: -56.1750 },
        viviendaPromovida: true,
        acceptedGuarantees: ["ANDA", "CGN"],
        utilityStatus: { saneamiento: "conectado", gas: "cañería", agua: "OSE", electricidad: "UTE" },
        energyLabel: "B",
        images: [
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=2000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=2000&auto=format&fit=crop"
        ],
        amenities: ["Lavadero", "Ascensor"],
        views: 589,
        publishedAt: "2026-02-16T08:00:00Z",
        updatedAt: "2026-02-17T09:00:00Z",
        featured: false,
        agentName: "Ana Silva",
        agentPhone: "+598 99 555 666",
    },
    {
        id: "8",
        slug: "lote-tahona",
        title: "Lote Exclusivo en Lomas de La Tahona",
        description: "Excelente terreno de 1000m² con fondo al lago.",
        type: "Terreno",
        operation: "Alquiler",
        badge: "Últimos Lotes",
        badgeColor: "bg-teal-600",
        price: 1500,
        currency: "USD",
        pricePerM2: 185,
        gastosComunes: 12000,
        bedrooms: 0,
        bathrooms: 0,
        area: 1000,
        builtArea: 0,
        garages: 0,
        floors: 0,
        yearBuilt: 0,
        department: "Canelones",
        city: "Camino de los Horneros",
        neighborhood: "La Tahona",
        address: "Mza 15",
        geolocation: { lat: -34.8000, lng: -55.9500 },
        viviendaPromovida: false,
        acceptedGuarantees: [],
        utilityStatus: { saneamiento: "conectado", gas: "sin servicio", agua: "OSE", electricidad: "UTE" },
        energyLabel: "A",
        images: [
            "https://images.unsplash.com/photo-1513584684374-8bab748fbf90?q=80&w=2000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=2000&auto=format&fit=crop"
        ],
        amenities: ["Seguridad 24hs"],
        views: 322,
        publishedAt: "2026-02-12T09:00:00Z",
        updatedAt: "2026-02-16T10:00:00Z",
        featured: false,
        agentName: "Martin Gomez",
        agentPhone: "+598 99 222 333",
    },
    {
        id: "9",
        slug: "oficina-cowork-ciudad-vieja",
        title: "Planta Corporativa en WTC",
        description: "Oficina moderna en edificio corporativo inteligente.",
        type: "Oficina",
        operation: "Alquiler",
        badge: "Corporativo",
        badgeColor: "bg-indigo-600",
        price: 85000,
        currency: "UYU",
        pricePerM2: 0,
        gastosComunes: 8000,
        bedrooms: 0,
        bathrooms: 2,
        area: 120,
        builtArea: 120,
        garages: 0,
        floors: 1,
        yearBuilt: 2010,
        department: "Montevideo",
        city: "Montevideo",
        neighborhood: "Buceo",
        address: "Plaza Independencia",
        geolocation: { lat: -34.9060, lng: -56.1980 },
        viviendaPromovida: false,
        acceptedGuarantees: ["Porto Seguro", "Sura", "BSE"],
        utilityStatus: { saneamiento: "conectado", gas: "sin servicio", agua: "OSE", electricidad: "UTE" },
        energyLabel: "B",
        images: [
            "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=2000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=2000&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=2000&auto=format&fit=crop"
        ],
        amenities: ["Ascensor", "Seguridad 24hs", "Aire Acondicionado"],
        views: 201,
        publishedAt: "2026-02-19T08:00:00Z",
        updatedAt: "2026-02-19T08:00:00Z",
        featured: true,
        agentName: "Diego Hernandez",
        agentPhone: "+598 99 666 777",
    }
]
"""

for path in data_ts_files:
    if not os.path.exists(path):
        continue
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    # Find where PROPERTIES starts
    start_str = "export const PROPERTIES: Property[] = ["
    start_idx = content.find(start_str)
    if start_idx == -1:
        continue
    
    # We will search from `[` specifically to ignore `Property[]` bracket
    search_start = start_idx + len(start_str) - 1
    
    bracket_count = 0
    in_array = False
    end_idx = -1
    for i in range(search_start, len(content)):
        if content[i] == '[':
            in_array = True
            bracket_count += 1
        elif content[i] == ']':
            bracket_count -= 1
            if in_array and bracket_count == 0:
                end_idx = i
                break
    
    if end_idx != -1:
        new_content = content[:start_idx] + MOCK_DATA + content[end_idx + 1:]
        with open(path, "w", encoding="utf-8") as f:
            f.write(new_content)
        print(f"Updated {path}")
